# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=100)),
                ('descr', models.TextField(max_length=1000)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qdisp', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
